// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQDt-TD7fHNLwh07G8bfuM-ju9mF5Gf74',
    appId: '1:96890905156:web:7981451a99467fd4ac9211',
    messagingSenderId: '96890905156',
    projectId: 'watchshopapp-5fe7d',
    authDomain: 'watchshopapp-5fe7d.firebaseapp.com',
    storageBucket: 'watchshopapp-5fe7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVqHqP0XW7LvthcL6mDBcmKlub2wQZTUs',
    appId: '1:96890905156:android:45d33466ffb396e9ac9211',
    messagingSenderId: '96890905156',
    projectId: 'watchshopapp-5fe7d',
    storageBucket: 'watchshopapp-5fe7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrz_WBHd-_6pQhBcCDFn0vvSLvyRc8LZg',
    appId: '1:96890905156:ios:88d68cfac8ebb3afac9211',
    messagingSenderId: '96890905156',
    projectId: 'watchshopapp-5fe7d',
    storageBucket: 'watchshopapp-5fe7d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrz_WBHd-_6pQhBcCDFn0vvSLvyRc8LZg',
    appId: '1:96890905156:ios:0a302627d37eb307ac9211',
    messagingSenderId: '96890905156',
    projectId: 'watchshopapp-5fe7d',
    storageBucket: 'watchshopapp-5fe7d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
